/** Declaration file generated by dts-gen */

declare module 'turndown' {
    export = turndown;

    class turndown {
        constructor(options?: any);

        addRule(key: any, rule: any): any;
        escape(string: any): any;
        keep(filter: any): any;
        remove(filter: any): any;
        turndown(input: any): string;
        use(plugin: any): any;
    }

    namespace turndown {
        function addRule(key: any, rule: any): any;
        function escape(string: any): any;
        function keep(filter: any): any;
        function remove(filter: any): any;
        function turndown(input: any): any;
        function use(plugin: any): any;

        namespace addRule {
            const prototype: {
            };

        }

        namespace escape {
            const prototype: {
            };
        }

        namespace keep {
            const prototype: {
            };
        }

        namespace remove {
            const prototype: {
            };
        }

        namespace turndown {
            const prototype: {
            };
        }

        namespace use {
            const prototype: {
            };
        }
    }
}